#!/usr/bin/env bash
# =============================================================================
# setup-aliases.sh — Host Aliases Setup
# Lives at: fedora_KDE_setup/setup-aliases.sh
#
# Installs aliases to ~/.bashrc.d/host-aliases.sh (Fedora's native mechanism).
# Guarded so they ONLY load on the host — never inside containers.
#
# Container-specific aliases are handled by each container's
# /etc/profile.d/zzz-*-custom.sh (set up by their install scripts).
#
# USAGE:
#   ./setup-aliases.sh              # install aliases
#   ./setup-aliases.sh --remove     # remove aliases file
#   ./setup-aliases.sh --show       # print what would be installed
#
# To add more aliases: edit the ALIASES section below, then re-run.
# =============================================================================

set -uo pipefail

ALIASES_DIR="$HOME/.bashrc.d"
ALIASES_FILE="$ALIASES_DIR/host-aliases.sh"

# --- Colors ---
if [[ -t 1 ]]; then
    BOLD=$'\e[1m'; NORMAL=$'\e[0m'
    GREEN=$'\e[32m'; YELLOW=$'\e[33m'; BLUE=$'\e[34m'; CYAN=$'\e[36m'
else
    BOLD=""; NORMAL=""; GREEN=""; YELLOW=""; BLUE=""; CYAN=""
fi

info() { echo -e "${BLUE}${BOLD}[INFO]${NORMAL}  $*"; }
ok()   { echo -e "${GREEN}${BOLD}[ OK ]${NORMAL}  $*"; }
warn() { echo -e "${YELLOW}${BOLD}[WARN]${NORMAL}  $*"; }

# =============================================================================
# CONTAINER SHORTCUTS — edit this to add/remove containers
# Format: NUMBER:CONTAINER_NAME:DESCRIPTION
# =============================================================================
CONTAINERS=(
    "1:ros1-anscer:ROS1 Noetic (ANSCER simulation)"
    "2:ros2-jazzy:ROS2 Jazzy (development)"
    "3:dev:Dev environment (C++ / Python / Go / Rust / CUDA)"
)

# =============================================================================
# Generate aliases file content
# =============================================================================
generate_aliases() {
cat <<'HEADER'
# =============================================================================
# Host Aliases — auto-generated by setup-aliases.sh
# Only loads on the host — skips inside distrobox/docker containers.
# Re-run setup-aliases.sh to update. Manual edits will be overwritten.
# =============================================================================

# Guard: skip if inside a container
[[ -n "${CONTAINER_ID:-}" ]] && return 0

HEADER

# --- Container entry shortcuts ---
cat <<'SECTION'
# =============================================================================
# Container Shortcuts
# =============================================================================
SECTION

for entry in "${CONTAINERS[@]}"; do
    IFS=':' read -r num name desc <<< "$entry"
    echo "alias ${num}='distrobox enter ${name}'    # ${desc}"
done

cat <<'SECTION'

# =============================================================================
# System Management
# =============================================================================
alias update='sudo dnf upgrade --refresh -y'
alias installed='dnf list --installed'
alias search='dnf search'
alias cleanup='sudo dnf autoremove -y && sudo dnf clean all'
alias reboot='sudo systemctl reboot'
alias poweroff='sudo systemctl poweroff'
alias services='systemctl list-units --type=service --state=running'
alias journal='journalctl -xe'
alias diskspace='df -h --type=btrfs --type=ext4'
alias bigfiles='du -sh ~/* | sort -rh | head -20'

# =============================================================================
# NVIDIA / GPU / ASUS
# =============================================================================
alias gpu='nvidia-smi'
alias gpuwatch='watch -n 1 nvidia-smi'
SECTION

# Add ASUS aliases only if asusctl exists
cat <<'SECTION'
# ASUS profiles (only work if asusctl is installed)
if command -v asusctl &>/dev/null; then
    alias performance='asusctl profile -P Performance'
    alias balanced='asusctl profile -P Balanced'
    alias quiet='asusctl profile -P Quiet'
    alias profile='asusctl profile -p'
fi

# GPU mode (only work if supergfxctl is installed)
if command -v supergfxctl &>/dev/null; then
    alias gpumode='supergfxctl -g'
    alias hybrid='sudo supergfxctl -m Hybrid'
    alias dgpu='sudo supergfxctl -m Dedicated'
    alias igpu='sudo supergfxctl -m Integrated'
fi

# =============================================================================
# Docker / Containers
# =============================================================================
alias d='docker'
alias dc='docker compose'
alias dps='docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"'
alias dpsa='docker ps -a --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"'
alias dimages='docker images --format "table {{.Repository}}\t{{.Tag}}\t{{.Size}}"'
alias dstop='docker stop $(docker ps -q) 2>/dev/null || echo "No running containers"'
alias dlogs='docker logs -f'
alias dexec='docker exec -it'
alias dprune='echo "This will remove all stopped containers, unused networks, dangling images, and build cache." && read -r -p "Continue? [y/N] " ans && [[ "$ans" =~ ^[Yy]$ ]] && docker system prune -af || echo "Cancelled"'

# Distrobox
alias db='distrobox'
alias dbl='distrobox list'
SECTION

# Generate dbe aliases dynamically from CONTAINERS array
echo ""
echo "# Quick enter aliases"
for entry in "${CONTAINERS[@]}"; do
    IFS=':' read -r num name desc <<< "$entry"
    echo "alias dbe-${name}='distrobox enter ${name}'"
done

cat <<'SECTION'

# =============================================================================
# Git
# =============================================================================
alias g='git'
alias gs='git status'
alias ga='git add'
alias gaa='git add -A'
alias gc='git commit -m'
alias gca='git commit --amend'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias gl='git pull'
alias gf='git fetch --all --prune'
alias glog='git log --oneline --graph --decorate -20'
alias gloga='git log --oneline --graph --decorate --all -30'
alias gd='git diff'
alias gds='git diff --staged'
alias gb='git branch'
alias gba='git branch -a'
alias gco='git checkout'
alias gsw='git switch'
alias gsc='git switch -c'
alias gcl='git clone'
alias gst='git stash'
alias gstp='git stash pop'
alias gcp='git cherry-pick'
alias grb='git rebase'
alias grbi='git rebase -i'
alias gm='git merge'

# =============================================================================
# Snapper (BTRFS snapshots)
# =============================================================================
alias snaplist='sudo snapper -c root list'
alias snapcreate='sudo snapper -c root create --description'
alias snapundo='sudo snapper -c root undochange'
alias snapdiff='sudo snapper -c root diff'

# =============================================================================
# Navigation
# =============================================================================
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ll='ls -alFh'
alias la='ls -A'
alias lt='ls -ltrh'
alias mkd='mkdir -pv'

# =============================================================================
# Quick directories
# =============================================================================
alias ros1='cd ~/anscer_ws'
alias ros2='cd ~/ros2-CONTAINER'
alias dev='cd ~/dev-CONTAINER'

# =============================================================================
# Editors
# =============================================================================
alias z='zed .'

# =============================================================================
# Misc
# =============================================================================
alias ports='ss -tulnp'
alias myip='curl -s ifconfig.me && echo'
alias weather='curl wttr.in/?format=3'
alias path='echo $PATH | tr ":" "\n"'
alias reload='source ~/.bashrc && echo "Reloaded"'
SECTION
}

# =============================================================================
# Main
# =============================================================================
case "${1:-}" in
    --remove)
        if [[ -f "$ALIASES_FILE" ]]; then
            rm "$ALIASES_FILE"
            ok "Removed $ALIASES_FILE"
            info "Run 'source ~/.bashrc' or open a new terminal"
        else
            warn "Nothing to remove"
        fi
        ;;

    --show)
        generate_aliases
        ;;

    *)
        mkdir -p "$ALIASES_DIR"

        if [[ -f "$ALIASES_FILE" ]]; then
            warn "Existing aliases file found — will be overwritten"
        fi

        generate_aliases > "$ALIASES_FILE"
        chmod 644 "$ALIASES_FILE"
        ok "Aliases installed to $ALIASES_FILE"

        # Verify ~/.bashrc sources ~/.bashrc.d/
        if grep -q 'bashrc\.d' "$HOME/.bashrc" 2>/dev/null; then
            ok "~/.bashrc already sources ~/.bashrc.d/"
        else
            warn "~/.bashrc doesn't source ~/.bashrc.d/"
            info "Add this to your ~/.bashrc:"
            echo '    if [ -d ~/.bashrc.d ]; then'
            echo '        for rc in ~/.bashrc.d/*; do'
            echo '            [ -f "$rc" ] && . "$rc"'
            echo '        done'
            echo '    fi'
        fi

        echo
        info "Run 'source ~/.bashrc' or open a new terminal to activate."
        echo
        echo -e "${BOLD}Container shortcuts:${NORMAL}"
        for entry in "${CONTAINERS[@]}"; do
            IFS=':' read -r num name desc <<< "$entry"
            echo -e "  ${CYAN}${num}${NORMAL}  →  distrobox enter ${name}  (${desc})"
        done
        echo
        echo -e "${BOLD}To add more containers:${NORMAL} edit CONTAINERS array in this script, re-run."
        echo -e "${BOLD}To customize aliases:${NORMAL} edit the generate_aliases() function, re-run."
        ;;
esac
