#!/usr/bin/env bash
# =============================================================================
# ssh-manager.sh — Multi-account GitHub SSH + Git Profile Manager
#
# Lives at: fedora_KDE_setup/ssh-manager.sh
# Works on: host, distrobox containers, docker containers (if home is mounted)
#
# Sets up:
#   1. Named SSH keys per GitHub account (no collisions)
#   2. ~/.ssh/config with Host aliases for each account
#   3. git-profile command for switching git identity per-repo
#
# USAGE:
#   ./ssh-manager.sh setup          # Interactive — set up all accounts
#   ./ssh-manager.sh list           # Show configured profiles
#   ./ssh-manager.sh test           # Test SSH connection for each account
#
# After setup, use in any repo:
#   git profile use work            # Switch to work identity
#   git profile use showcase        # Switch to showcase identity
#   git profile use personal        # Switch to personal identity
#   git profile show                # Show current identity
#
# For repos that use a non-default account, use the Host alias in URLs:
#   git clone git@github-work:company/repo.git
#   git clone git@github-showcase:myuser/portfolio.git
#   git clone git@github.com:myuser/personal-repo.git   (default)
# =============================================================================

set -uo pipefail

SSH_DIR="$HOME/.ssh"
SSH_CONFIG="$SSH_DIR/config"
GIT_PROFILE_BIN="$HOME/.local/bin/git-profile"

# --- Colors ---
if [[ -t 1 ]]; then
    BOLD=$'\e[1m'; NORMAL=$'\e[0m'
    RED=$'\e[31m'; GREEN=$'\e[32m'; YELLOW=$'\e[33m'; BLUE=$'\e[34m'; CYAN=$'\e[36m'
else
    BOLD=""; NORMAL=""; RED=""; GREEN=""; YELLOW=""; BLUE=""; CYAN=""
fi

info()  { echo -e "${BLUE}${BOLD}[INFO]${NORMAL}  $*"; }
ok()    { echo -e "${GREEN}${BOLD}[ OK ]${NORMAL}  $*"; }
warn()  { echo -e "${YELLOW}${BOLD}[WARN]${NORMAL}  $*"; }
err()   { echo -e "${RED}${BOLD}[FAIL]${NORMAL}  $*"; }

# =============================================================================
# PROFILES — edit these to add/remove accounts
# Format: PROFILES[alias]="description"
# =============================================================================
declare -A PROFILES
PROFILES=(
    [personal]="Personal GitHub (default — used for git@github.com URLs)"
    [work]="Work GitHub (used for git@github-work URLs)"
    [showcase]="Portfolio/Showcase GitHub (used for git@github-showcase URLs)"
)

# The default profile — used when cloning with standard git@github.com URLs
DEFAULT_PROFILE="personal"

# =============================================================================
# setup_account — generate SSH key + collect git identity for one profile
# =============================================================================
setup_account() {
    local profile="$1"
    local description="${PROFILES[$profile]}"
    local key_file="$SSH_DIR/id_ed25519_github_${profile}"

    echo
    echo -e "${BOLD}${CYAN}--- Setting up: $profile ---${NORMAL}"
    echo -e "${BOLD}$description${NORMAL}"
    echo

    # SSH key
    if [[ -f "$key_file" ]]; then
        info "SSH key already exists: $key_file"
        read -r -p "Regenerate? [y/N] " regen
        if [[ ! "$regen" =~ ^[Yy]$ ]]; then
            ok "Kept existing key"
        else
            read -r -p "Email for this account: " email
            ssh-keygen -t ed25519 -C "$email" -f "$key_file" -N "" \
                || { err "Key generation failed"; return 1; }
            ok "Key regenerated"
        fi
    else
        read -r -p "Email for this account: " email
        ssh-keygen -t ed25519 -C "$email" -f "$key_file" -N "" \
            || { err "Key generation failed"; return 1; }
        ok "Key generated: $key_file"
    fi

    # Git identity
    local git_name git_email
    read -r -p "Git user.name for '$profile': " git_name
    read -r -p "Git user.email for '$profile': " git_email

    # Store git identity in a profile file
    local profile_file="$SSH_DIR/git-profile-${profile}"
    cat > "$profile_file" <<EOF
GIT_PROFILE_NAME="$git_name"
GIT_PROFILE_EMAIL="$git_email"
GIT_PROFILE_KEY="$key_file"
EOF
    chmod 600 "$profile_file"
    ok "Git identity saved for '$profile'"
}

# =============================================================================
# write_ssh_config — generate ~/.ssh/config with Host aliases
# =============================================================================
write_ssh_config() {
    info "Writing SSH config..."

    # Backup existing
    [[ -f "$SSH_CONFIG" ]] && cp "$SSH_CONFIG" "${SSH_CONFIG}.bak.$(date +%Y%m%d-%H%M%S)"

    cat > "$SSH_CONFIG" <<'HEADER'
# =============================================================================
# GitHub Multi-Account SSH Configuration
# Generated by ssh-manager.sh — edit PROFILES in the script to change accounts
# =============================================================================

HEADER

    for profile in "${!PROFILES[@]}"; do
        local key_file="$SSH_DIR/id_ed25519_github_${profile}"
        [[ ! -f "$key_file" ]] && continue

        if [[ "$profile" == "$DEFAULT_PROFILE" ]]; then
            # Default profile uses standard github.com hostname
            cat >> "$SSH_CONFIG" <<EOF
# $profile (DEFAULT — git@github.com URLs use this)
Host github.com
    HostName github.com
    User git
    IdentityFile $key_file
    IdentitiesOnly yes

EOF
        else
            # Non-default profiles use aliased hostnames
            cat >> "$SSH_CONFIG" <<EOF
# $profile (use git@github-${profile}:user/repo.git)
Host github-${profile}
    HostName github.com
    User git
    IdentityFile $key_file
    IdentitiesOnly yes

EOF
        fi
    done

    chmod 600 "$SSH_CONFIG"
    ok "SSH config written to $SSH_CONFIG"
}

# =============================================================================
# install_git_profile — create the git-profile subcommand
# =============================================================================
install_git_profile() {
    info "Installing git-profile command..."

    mkdir -p "$(dirname "$GIT_PROFILE_BIN")"

    cat > "$GIT_PROFILE_BIN" <<'GITPROFILE'
#!/usr/bin/env bash
# git-profile — switch git identity per-repo or globally
# Usage:
#   git profile use <profile>        Set identity for current repo
#   git profile use <profile> -g     Set identity globally
#   git profile show                 Show current repo identity
#   git profile list                 List available profiles

set -uo pipefail

SSH_DIR="$HOME/.ssh"

case "${1:-}" in
    use)
        profile="${2:-}"
        [[ -z "$profile" ]] && { echo "Usage: git profile use <profile> [-g]"; exit 1; }

        profile_file="$SSH_DIR/git-profile-${profile}"
        [[ ! -f "$profile_file" ]] && { echo "Profile '$profile' not found. Run: ssh-manager.sh list"; exit 1; }

        source "$profile_file"

        scope="--local"
        scope_label="repo"
        [[ "${3:-}" == "-g" ]] && { scope="--global"; scope_label="global"; }

        # Fall back to global if not inside a git repo
        if [[ "$scope" == "--local" ]] && ! git rev-parse --is-inside-work-tree &>/dev/null; then
            scope="--global"
            scope_label="global (not in a repo)"
        fi

        git config $scope user.name "$GIT_PROFILE_NAME"
        git config $scope user.email "$GIT_PROFILE_EMAIL"
        echo "Switched to '$profile' ($scope_label): $GIT_PROFILE_NAME <$GIT_PROFILE_EMAIL>"

        # Update origin remote URL to use the correct SSH host alias
        if [[ "$scope" == "--local" ]] && git remote get-url origin &>/dev/null; then
            current_url="" old_host="" new_host="" new_url=""
            current_url=$(git remote get-url origin)

            # Only modify SSH URLs (git@...)
            if [[ "$current_url" == git@* ]]; then
                # Extract current host (everything between @ and :)
                old_host=$(echo "$current_url" | sed 's/git@\([^:]*\):.*/\1/')

                # Determine new host based on profile
                if [[ "$profile" == "personal" ]]; then
                    new_host="github.com"
                else
                    new_host="github-${profile}"
                fi

                if [[ "$old_host" != "$new_host" ]]; then
                    new_url=$(echo "$current_url" | sed "s|git@${old_host}:|git@${new_host}:|")
                    git remote set-url origin "$new_url"
                    echo "Remote updated: $old_host → $new_host"
                fi
            fi
        fi
        ;;

    show)
        name=$(git config user.name 2>/dev/null || echo "(not set)")
        email=$(git config user.email 2>/dev/null || echo "(not set)")
        echo "Current: $name <$email>"

        # Show which profile matches
        for f in "$SSH_DIR"/git-profile-*; do
            [[ -f "$f" ]] || continue
            source "$f"
            if [[ "$GIT_PROFILE_EMAIL" == "$email" ]]; then
                pname=$(basename "$f" | sed 's/git-profile-//')
                echo "Profile: $pname"
                break
            fi
        done
        ;;

    list)
        echo "Available profiles:"
        for f in "$SSH_DIR"/git-profile-*; do
            [[ -f "$f" ]] || continue
            source "$f"
            pname=$(basename "$f" | sed 's/git-profile-//')
            echo "  $pname: $GIT_PROFILE_NAME <$GIT_PROFILE_EMAIL>"
        done
        ;;

    *)
        echo "Usage: git profile <use|show|list>"
        echo "  use <profile> [-g]   Set identity (per-repo or -g global)"
        echo "  show                 Show current identity"
        echo "  list                 List available profiles"
        ;;
esac
GITPROFILE

    chmod +x "$GIT_PROFILE_BIN"
    ok "git-profile installed to $GIT_PROFILE_BIN"
    info "Make sure ~/.local/bin is in your PATH"
}

# =============================================================================
# show_public_keys — print all public keys for user to add to GitHub
# =============================================================================
show_public_keys() {
    echo
    echo -e "${BOLD}${YELLOW}Add each public key to the corresponding GitHub account:${NORMAL}"
    echo -e "${BOLD}${YELLOW}GitHub → Settings → SSH and GPG Keys → New SSH Key${NORMAL}"

    for profile in "${!PROFILES[@]}"; do
        local pub_file="$SSH_DIR/id_ed25519_github_${profile}.pub"
        if [[ -f "$pub_file" ]]; then
            echo
            echo -e "${BOLD}${CYAN}=== $profile ===${NORMAL}"
            cat "$pub_file"
        fi
    done
    echo
}

# =============================================================================
# test_connections — test SSH auth for each profile
# =============================================================================
test_connections() {
    echo
    info "Testing SSH connections..."

    for profile in "${!PROFILES[@]}"; do
        local key_file="$SSH_DIR/id_ed25519_github_${profile}"
        [[ ! -f "$key_file" ]] && { warn "$profile: no key found"; continue; }

        local host="github.com"
        [[ "$profile" != "$DEFAULT_PROFILE" ]] && host="github-${profile}"

        local result
        result=$(ssh -T -o StrictHostKeyChecking=accept-new -o ConnectTimeout=10 "git@${host}" 2>&1 || true)
        if echo "$result" | grep -q "successfully authenticated"; then
            ok "$profile ($host): authenticated"
        else
            warn "$profile ($host): $result"
        fi
    done
    echo
}

# =============================================================================
# list_profiles — show configured profiles
# =============================================================================
list_profiles() {
    echo
    echo -e "${BOLD}Configured GitHub profiles:${NORMAL}"
    for profile in "${!PROFILES[@]}"; do
        local key_file="$SSH_DIR/id_ed25519_github_${profile}"
        local profile_file="$SSH_DIR/git-profile-${profile}"
        local status="${RED}NOT SET UP${NORMAL}"

        if [[ -f "$key_file" ]] && [[ -f "$profile_file" ]]; then
            source "$profile_file"
            local host="github.com"
            [[ "$profile" != "$DEFAULT_PROFILE" ]] && host="github-${profile}"
            status="${GREEN}$GIT_PROFILE_NAME <$GIT_PROFILE_EMAIL>${NORMAL} → git@${host}"
        fi

        local default_tag=""
        [[ "$profile" == "$DEFAULT_PROFILE" ]] && default_tag=" ${YELLOW}(default)${NORMAL}"

        echo -e "  ${BOLD}$profile${NORMAL}${default_tag}: $status"
    done
    echo
}

# =============================================================================
# MAIN
# =============================================================================
main() {
    mkdir -p "$SSH_DIR"
    chmod 700 "$SSH_DIR"

    case "${1:-}" in
        setup)
            echo
            echo -e "${BOLD}${CYAN}========================================${NORMAL}"
            echo -e "${BOLD}${CYAN}  GitHub Multi-Account SSH Setup${NORMAL}"
            echo -e "${BOLD}${CYAN}========================================${NORMAL}"
            echo
            info "This will set up ${#PROFILES[@]} GitHub accounts:"
            for profile in "${!PROFILES[@]}"; do
                local default_tag=""
                [[ "$profile" == "$DEFAULT_PROFILE" ]] && default_tag=" (default)"
                echo "  - $profile${default_tag}: ${PROFILES[$profile]}"
            done
            echo
            read -r -p "Continue? [Y/n] " confirm
            [[ "$confirm" =~ ^[Nn]$ ]] && { info "Cancelled."; exit 0; }

            for profile in "${!PROFILES[@]}"; do
                setup_account "$profile"
            done

            write_ssh_config
            install_git_profile

            show_public_keys
            read -r -p "Press Enter after adding ALL public keys to their GitHub accounts..." _

            test_connections

            echo -e "${GREEN}${BOLD}Setup complete!${NORMAL}"
            echo
            echo "Usage in any repo:"
            echo "  git profile use work       # switch to work identity"
            echo "  git profile use showcase   # switch to showcase identity"
            echo "  git profile use personal   # switch to personal identity"
            echo "  git profile show           # show current identity"
            echo
            echo "Clone with specific accounts:"
            echo "  git clone git@github.com:user/repo.git          # personal (default)"
            echo "  git clone git@github-work:company/repo.git      # work"
            echo "  git clone git@github-showcase:user/repo.git     # showcase"
            ;;

        list)
            list_profiles
            ;;

        test)
            test_connections
            ;;

        *)
            echo "Usage: $0 <setup|list|test>"
            echo "  setup   Interactive setup of all GitHub accounts"
            echo "  list    Show configured profiles"
            echo "  test    Test SSH connections"
            ;;
    esac
}

main "$@"
